export const STORAGE_KEYS = {
  questions: 'quiz.workspace.questions',
  config: 'quiz.workspace.config',
  history: 'quiz.workspace.history',
  user: 'quiz.workspace.user',
};

export const HISTORY_LIMIT = 20;

export const GAME_MODES = {
  study: {
    label: 'Nauka',
    description: 'Spokojny tryb z wyjaśnieniami i opcjonalnym retry błędnych pytań.',
    timeMultiplier: 1,
    streakMultiplier: 1,
    showAnswerDetails: true,
    showExplanationInReview: true,
    showPercentageScore: false,
    defaultTimerEnabled: false,
    allowTimerToggle: true,
    allowRetryToggle: true,
    accent: 'Idealny na spokojne budowanie wiedzy i poprawki po rundzie.',
    preset: {
      category: 'focus',
      limit: 7,
      timeLimit: 20,
      shuffle: false,
      timerEnabled: false,
      retryIncorrect: true,
    },
  },
  exam: {
    label: 'Egzamin',
    description: 'Bez podpowiedzi w trakcie, z obowiązkowym timerem i procentowym wynikiem końcowym.',
    timeMultiplier: 0.8,
    streakMultiplier: 1,
    showAnswerDetails: false,
    showExplanationInReview: false,
    showPercentageScore: true,
    defaultTimerEnabled: true,
    allowTimerToggle: false,
    allowRetryToggle: false,
    forceTimer: true,
    accent: 'Tryb sprawdzający wiedzę pod presją czasu.',
    preset: {
      category: 'focus',
      limit: 10,
      timeLimit: 18,
      shuffle: true,
      timerEnabled: true,
      retryIncorrect: false,
    },
  },
  blitz: {
    label: 'Blitz 60',
    description: 'Szybka minigra: tempo, punkty za serię i presja czasu.',
    timeMultiplier: 0.6,
    streakMultiplier: 2,
    showAnswerDetails: false,
    showExplanationInReview: true,
    showPercentageScore: false,
    defaultTimerEnabled: true,
    allowTimerToggle: true,
    allowRetryToggle: false,
    accent: 'Minigra czasowa dla fanów szybkich decyzji.',
    preset: {
      category: 'all',
      limit: 8,
      timeLimit: 10,
      shuffle: true,
      timerEnabled: true,
      retryIncorrect: false,
    },
  },
  survival: {
    label: 'Survival',
    description: 'Pomyłka kończy rundę. Liczy się seria i ostrożność.',
    timeMultiplier: 0.8,
    streakMultiplier: 3,
    showAnswerDetails: true,
    showExplanationInReview: true,
    showPercentageScore: false,
    defaultTimerEnabled: true,
    allowTimerToggle: true,
    allowRetryToggle: false,
    accent: 'Tryb przetrwania dla skupionych graczy.',
    preset: {
      category: 'all',
      limit: 10,
      timeLimit: 12,
      shuffle: true,
      timerEnabled: true,
      retryIncorrect: false,
    },
  },
  arcade: {
    label: 'Arcade Sprint',
    description: 'Odpowiedzi tasują się w locie, a Ty łapiesz poprawną pod presją.',
    timeMultiplier: 0.7,
    streakMultiplier: 3,
    showAnswerDetails: true,
    showExplanationInReview: true,
    showPercentageScore: false,
    defaultTimerEnabled: true,
    allowTimerToggle: true,
    allowRetryToggle: false,
    accent: 'Zręcznościówka ucząca przez ruch i tempo.',
    dynamicAnswers: true,
    preset: {
      category: 'all',
      limit: 8,
      timeLimit: 9,
      shuffle: true,
      timerEnabled: true,
      retryIncorrect: false,
    },
  },
  runner: {
    label: 'Code Runner 2D',
    description: 'Sterujesz informatykiem po torach i wpadasz w dobrą odpowiedź, zanim dystans spadnie do zera.',
    timeMultiplier: 0.85,
    streakMultiplier: 3,
    showAnswerDetails: true,
    showExplanationInReview: true,
    showPercentageScore: false,
    defaultTimerEnabled: true,
    allowTimerToggle: false,
    allowRetryToggle: false,
    forceTimer: true,
    accent: 'Pytanie u góry, ruch na strzałkach i odpowiedzi pędzące prosto na Ciebie.',
    runnerChallenge: true,
    preset: {
      category: 'focus',
      limit: 7,
      timeLimit: 14,
      shuffle: true,
      timerEnabled: true,
      retryIncorrect: false,
    },
  },
  mentor: {
    label: 'Mentor Combo',
    description: 'Seria pytań z większą premią za poprawne odpowiedzi i edukacyjnym review.',
    timeMultiplier: 1.1,
    streakMultiplier: 2,
    showAnswerDetails: true,
    showExplanationInReview: true,
    showPercentageScore: false,
    defaultTimerEnabled: true,
    allowTimerToggle: true,
    allowRetryToggle: false,
    accent: 'Tryb ćwiczący regularność i zapamiętywanie.',
    preset: {
      category: 'focus',
      limit: 6,
      timeLimit: 24,
      shuffle: false,
      timerEnabled: true,
      retryIncorrect: false,
    },
  },
};

export const DEFAULT_CONFIG = {
  mode: 'study',
  category: 'all',
  limit: 5,
  timeLimit: 20,
  shuffle: true,
  timerEnabled: false,
  retryIncorrect: true,
};

export const DEFAULT_USER = {
  nickname: 'Gracz lokalny',
  email: 'local@quiz.app',
  weeklyGoal: 30,
  focus: 'frontend',
};
