export const fallbackQuestions = [
  {
    id: 'frontend-1',
    content: 'Jakiego hooka używa się do stanu lokalnego w React?',
    answers: ['useMemo', 'useEffect', 'useState', 'useRef'],
    correctAnswer: 'useState',
    category: 'frontend',
    explanation: 'useState pozwala przechowywać i aktualizować stan komponentu.',
  },
  {
    id: 'frontend-2',
    content: 'Która właściwość CSS ustawia układ flex?',
    answers: ['display: grid', 'display: block', 'display: flex', 'position: sticky'],
    correctAnswer: 'display: flex',
    category: 'frontend',
    explanation: 'display: flex włącza model flexbox dla kontenera.',
  },
  {
    id: 'backend-1',
    content: 'Który kod HTTP zwykle oznacza poprawne utworzenie zasobu?',
    answers: ['200', '201', '204', '404'],
    correctAnswer: '201',
    category: 'backend',
    explanation: 'HTTP 201 Created potwierdza utworzenie nowego zasobu.',
  },
  {
    id: 'backend-2',
    content: 'Do czego służy indeks w relacyjnej bazie danych?',
    answers: ['Do szyfrowania', 'Do przyspieszania zapytań', 'Do kompresji obrazów', 'Do logowania błędów'],
    correctAnswer: 'Do przyspieszania zapytań',
    category: 'backend',
    explanation: 'Indeksy przyspieszają wyszukiwanie i sortowanie danych.',
  },
  {
    id: 'web-1',
    content: 'Która metoda HTTP zwykle pobiera dane bez modyfikacji zasobu?',
    answers: ['POST', 'PATCH', 'GET', 'DELETE'],
    correctAnswer: 'GET',
    category: 'web',
    explanation: 'GET służy do odczytu danych i powinien być bezpieczny oraz idempotentny.',
  },
  {
    id: 'web-2',
    content: 'Co oznacza skrót URL?',
    answers: ['Uniform Resource Locator', 'Unified Request Link', 'Universal Routing Layer', 'User Resource Log'],
    correctAnswer: 'Uniform Resource Locator',
    category: 'web',
    explanation: 'URL to standardowy adres zasobu w sieci.',
  },
  {
    id: 'devops-1',
    content: 'Które narzędzie najczęściej służy do konteneryzacji aplikacji?',
    answers: ['Docker', 'Vite', 'Jest', 'Figma'],
    correctAnswer: 'Docker',
    category: 'devops',
    explanation: 'Docker pozwala pakować aplikacje w kontenery.',
  },
  {
    id: 'security-1',
    content: 'Która praktyka pomaga ograniczyć skutki wycieku hasła?',
    answers: ['Logowanie bez HTTPS', 'MFA', 'Tylko localhost', 'Minifikacja JS'],
    correctAnswer: 'MFA',
    category: 'security',
    explanation: 'Wieloskładnikowe uwierzytelnianie zmniejsza ryzyko przejęcia konta.',
  },
];
